const constants = {
  PAGE_TITLE: {
    ANIMAL_CATEGORY_EDIT: 'Animal Category Edit',
    POST_EDIT: 'Post Edit',
    ANIMAL_CATEGORY_ADD: 'Add New Animal Category',
    POST_ADD: 'Add New Post',
    NOTIFICATION_TYPE_EDIT: 'Notification Type Edit',
    NOTIFICATION_TYPE_ADD: 'Add New Notification Type',
    ANIMAL_TYPE_EDIT: 'Animal Type Edit',
    ANIMAL_TYPE_ADD: 'Add New Animal Type',
    USER_EDIT: 'User Edit',
    USER_ADD: 'Add New User',
    VET_PRACTICE_EDIT: 'Vet Practice Edit',
    VET_PRACTICE_ADD: 'Add New Vet Practice',
    STORE_EDIT: 'Store Edit',
    STORE_ADD: 'Add New Store',
    ANIMAL_PROFILE_EDIT: 'Animal Profile Edit',
    ANIMAL_PROFILE_ADD: 'Add New Animal Profile',
    QUESTION_EDIT: 'Frequently Asked Questions Edit',
    QUESTION_ADD: 'Add New Frequently Asked Questions',
    NUTRITION_ADVICES_EDIT: 'Health Concerns Edit',
    NUTRITION_ADVICES_ADD: 'Add New Health Concerns',
    WELLBEING_ADVICES_EDIT: 'Wellbeing Advices Edit',
    WELLBEING_ADVICES_ADD: 'Add New Wellbeing Advices',
    BREED_ADD: 'Add New Breed',
    BREED_EDIT: 'Breed Edit',
    PROFILE: 'Profile',
    CMS_EDIT: 'CMS Edit',
    FORUM_ADD: 'Add new Forum',
    FORUM_EDIT: 'Forum Edit',
    ADVERTISEMENT_ADD: 'Add new Advertisement',
    ADVERTISEMENT_EDIT: 'Advertisement Edit',
    SUBSCRIPTION_ADD: 'Add new Subscription',
    SUBSCRIPTION_EDIT: 'Subscription Edit',
    SUBSCRIPTION_LIST: 'Subscription List',
    REPORT_POST_VIEW: 'Report',
    REPORT_POST_LIST: "Report post list",
    FAN_PAGE_LIST: "Page list",
    FAN_PAGE_ADD: "Add new page",
    FAN_PAGE_EDIT: "Edit page",
    FAN_PAGE_POST_ADD: 'Add New Fan Page Post',
    FAN_PAGE_POST_EDIT: 'Fan Page Post Edit',
    COUNTRY_LIST: 'Country list',
    COUNTRY_ADD: 'Add Country',
    COUNTRY_EDIT: 'Country Edit',
    STATE_LIST: 'State list',
    STATE_ADD: 'Add State',
    STATE_EDIT: 'State Edit',
    SPECIALITY_LIST: 'Speciality list',
    SPECIALITY_ADD: 'Add Speciality',
    SPECIALITY_EDIT: 'Speciality Edit',
    SPECIALIZATION_LIST: 'Specialization list',
    SPECIALIZATION_ADD: 'Add Specialization',
    SPECIALIZATION_EDIT: 'Specialization Edit',
    CHIP_LIST: 'Chip list',
    CHIP_ADD: 'Add Chip',
    CHIP_EDIT: 'Chip Edit',
    INSURER_LIST: 'Insurer list',
    INSURER_ADD: 'Add Insurer',
    INSURER_EDIT: 'Insurer Edit',
    CLASSIFICATION_LIST: 'Classification list',
    CLASSIFICATION_ADD: 'Add Classification',
    CLASSIFICATION_EDIT: 'Classification Edit',
    STORE_CLASSIFICATION_LIST: 'Store Classification list',
    STORE_CLASSIFICATION_ADD: 'Add Store Classification',
    STORE_CLASSIFICATION_EDIT: 'Store Classification Edit',
    PRACTICE_SERVICE_LIST: 'Practice Service list',
    PET_SERVICE_LIST: 'Pet Service list',
    PRACTICE_SERVICE_ADD: 'Add Practice Service',
    PET_SERVICE_ADD: 'Add pet Service',
    PRACTICE_SERVICE_EDIT: 'Practice Service Edit',
    PET_SERVICE_EDIT: 'Pet Service Edit',
    GROOMER_SERVICE_LIST: 'Groomer Service list',
    GROOMER_SERVICE_ADD: 'Add Groomer Service',
    GROOMER_SERVICE_EDIT: 'Groomer Service Edit',
    WALKER_SERVICE_LIST: 'Walker Service list',
    WALKER_SERVICE_ADD: 'Add Walker Service',
    WALKER_SERVICE_EDIT: 'Walker Service Edit',
    THERAPIST_SERVICE_LIST: 'Therapist Service list',
    THERAPIST_SERVICE_ADD: 'Add Therapist Service',
    THERAPIST_SERVICE_EDIT: 'Therapist Service Edit',
    NUTRITIONIST_SERVICE_LIST: 'Nutritionist Service list',
    NUTRITIONIST_SERVICE_ADD: 'Add Nutritionist Service',
    NUTRITIONIST_SERVICE_EDIT: 'Nutritionist Service Edit',
    BREEDER_SERVICE_LIST: 'Breeder Service list',
    BREEDER_SERVICE_ADD: 'Add Breeder Service',
    BREEDER_SERVICE_EDIT: 'Breeder Service Edit',
    SETTING_LIST: 'Setting list',
    SETTING_EDIT: 'Setting Edit',
    PRACTITIONER_LIABILITY_LIST: 'Practitioner Liability list',
    PRACTITIONER_LIABILITY_ADD: 'Add Practitioner Liability',
    PRACTITIONER_LIABILITY_EDIT: 'Practitioner Liability Edit',
    SERVICE_PROVIDER_LIABILITY_LIST: 'Service Provider Liability list',
    SERVICE_PROVIDER_LIABILITY_ADD: 'Add Service Provider Liability',
    SERVICE_PROVIDER_LIABILITY_EDIT: 'Service Provider Liability Edit',
    REPORT_REASON_LIST: 'Report Reason list',
    REPORT_REASON_ADD: 'Add Report Reason',
    REPORT_REASON_EDIT: 'Report Reason Edit',
    SYMPTOMS_HOW_LONG_LIST: 'Symptoms Duration list',
    SYMPTOMS_HOW_LONG_ADD: 'Add Symptoms Duration',
    SYMPTOMS_HOW_LONG_EDIT: 'Symptoms Duration Edit',
    MIAN_SERVICE_ADD: 'Add New Service',

  },

  VET_PRACTICE_HEADING: [
    "practice_name",
    "public_email",
    "address",
    "address2",
    "country",
    "state",
    "city",
    "zip_code",
    "int_code",
    "business_phone",
    "out_of_hours_number",
    "email_address",
    "website",
    "treated_type_of_pets_animal",
    "area_of_interest_or_specialisations",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "practice_accreditation_no",
    "classification",
    "lat",
    "long",
    "first_name",
    "last_name",
    "practice_service"
  ],
  VET_STORE_HEADING: [
    "store_name",
    "public_email",
    "address",
    "address2",
    "country",
    "state",
    "city",
    "zip_code",
    "int_code",
    "business_phone",
    "out_of_hours_number",
    "email_address",
    "website",
    "treated_type_of_pets_animal",
    "area_of_interest_or_specialisations",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "store_accreditation_no",
    "classification",
    "lat",
    "long",
    "first_name",
    "last_name",
    "store_service",
  ],
  VET_USER_HEADING: [
    "email",
    "role",
    "first_name",
    "last_name",
    "dob",
    "mobile",
    "address1",
    "address2",
    "country",
    "state",
    "city",
    "zip_code",
    "int_code",
    "education",
    "veterinary_registrations",
    "treats_type_animal",
    "specialization",
    "latitude",
    "longitude",
    "personal_bio",
    "registration_number",
    "practice_Email",
    "currency_type",
    "in_clinic_consultation",
    "online_consultation",
    "educationDuration",
    "passout_date",
    "practitioner_liability",
    "mon",
    "tue",
    "wed",
    "thu",
    "fri",
    "sat",
    "sun",
    "confirmed",
    "public_email",
    "public_contact_no",
    "public_contact_no_int_code",
    "public_out_of_hr_phone",
    "public_out_of_hr_phone_int_code",
    "b_user_name",
    "b_user_email",
    "b_country",
    "b_currency",
    "b_account_number",
    "b_iban",
    "b_ncc",
    "b_sort_code",
    "b_swiftbic",
    "bank_name",
    "b_address"
  ],
  SERVICE_PROVIDER: [
    "email",
    "role",
    "first_name",
    "last_name",
    "dob",
    "mobile",
    "address1",
    "address2",
    "country",
    "state",
    "city",
    "zip_code",
    "int_code",
    "personal_bio",
    "public_email",
    "public_contact_no",
    "public_contact_no_int_code",
    "public_out_of_hr_phone",
    "public_out_of_hr_phone_int_code",
    "currency_type",
    "treats_type_animal",
    "store_email",
    "sub_service_and_pricing",
    "mon",
    "tue",
    "wed",
    "thu",
    "fri",
    "sat",
    "sun",
    "b_user_name",
    "b_user_email",
    "b_country",
    "b_currency",
    "b_account_number",
    "b_iban",
    "b_ncc",
    "b_sort_code",
    "b_swiftbic",
    "bank_name",
    "b_address",
    "service_provider_liability"
  ],
  SOCKET_EVENTS: {
    forceServerDisconnect: 'force-server-disconnect',
    systemMessage: 'system-message',
    privateMessage: 'private-message',
    groupMessage: 'group-message',
    broadcastMessage: 'broadcast-message',
    connection: 'connection',
    disconnected: 'disconnected',
    logout: 'logout'
  }
};

export default constants;
