import { Router } from 'express';

import dashboard from './routes/dashboard';
import auth from './routes/auth';
import user from './routes/user';
import animalCategory from './routes/animal-category';
import profile from './routes/profile';
import breed from './routes/breeds';
import frequentlyAskedQuestions from './routes/frequently-asked-questions';
import nutritionAdvices from './routes/nutrition-advices';
import wellbeingAdvices from './routes/wellbeing-advices';
import animalType from './routes/animal-type';
import contactUs from './routes/contact-us';
import cookiePolicy from './routes/cookies-policy';
import privacyPolicy from './routes/privacy-policy';
import termsCondition from './routes/terms-condition';
import notificationType from './routes/notification-type';
import animalProfile from './routes/animal-profile';
import vetPractice from './routes/vet-practice';
import cms from './routes/cms';
import practiceUser from './routes/practice-user';
import appointments from './routes/appointments';
import unavailabilties from './routes/unavailabilties';
import forum from './routes/forum';
import forumAnswers from './routes/forum-answers';
import posts from './routes/posts';
import postComments from './routes/post-comments';
import reportPosts from './routes/report-posts';
import fanPages from './routes/fan-pages';
import fanPagesFollower from './routes/fan-pages-followers';
import fanPagePosts from './routes/fan-page-posts';
import fanPagePostsComments from './routes/fan-page-posts-comments';
import countryDropDowns from './routes/country-drop-downs';
import stateDropDowns from './routes/state-drop-downs';
import specialities from './routes/specialities';
import specialization from './routes/specialization';
import chips from './routes/chip-lists';
import insurers from './routes/insurer-lists';
import classifications from './routes/classifications';
import storeClassifications from './routes/store-classifications';
import practiceServices from './routes/practice-services';
import petServices from './routes/pet-service';
import settings from './routes/settings';
import practitionerLiabilities from './routes/practitioner-liabilities';
import serviceProviderLiabilities from './routes/service-provider-liability';
import reportReason from './routes/report-reasons';
import symptomsHowLong from './routes/symptoms-how-long';
import groomerServices from './routes/groomers-services';
import walkerServices from './routes/walkers-services';
import therapistServices from './routes/therapists-services';
import nutritionistServices from './routes/nutritionists-services';
import breederServices from './routes/breeders-services';
import advertisements from './routes/advertisement';
import subscriptions from './routes/subscription';
import superAdmin from './routes/super-admin';
import mesaage from './routes/messages';
import store from './routes/store';
import mainService from './routes/service-provider-main-service';
import subService from './routes/service-provider-sub-service';
import invoice from './routes/invoice';

export default () => {
  const router = Router();
  auth(router);
  dashboard(router);
  user(router);
  animalCategory(router);
  profile(router);
  breed(router);
  frequentlyAskedQuestions(router);
  nutritionAdvices(router);
  wellbeingAdvices(router);
  animalType(router);
  contactUs(router);
  cookiePolicy(router);
  privacyPolicy(router);
  termsCondition(router);
  notificationType(router);
  animalProfile(router);
  vetPractice(router);
  cms(router);
  practiceUser(router);
  appointments(router);
  unavailabilties(router);
  forum(router);
  forumAnswers(router);
  posts(router);
  postComments(router);
  reportPosts(router);
  fanPages(router);
  fanPagesFollower(router);
  fanPagePosts(router);
  fanPagePostsComments(router);
  countryDropDowns(router);
  stateDropDowns(router);
  specialities(router);
  specialization(router);
  chips(router);
  insurers(router);
  classifications(router);
  practiceServices(router);
  petServices(router);
  settings(router);
  practitionerLiabilities(router);
  serviceProviderLiabilities(router);
  reportReason(router);
  symptomsHowLong(router);
  groomerServices(router);
  walkerServices(router);
  therapistServices(router);
  nutritionistServices(router);
  breederServices(router);
  advertisements(router);
  subscriptions(router);
  superAdmin(router);
  mesaage(router);
  store(router);
  mainService(router);
  subService(router);
  invoice(router);
  storeClassifications(router);
  return router;
};
